Universidad Galileo  
Maestría en Data Science  
Statistical Learning II
Sección U  


   # **Practica 4: Backpropagation**


<p style="text-align: right;">
Henry Giovanni<br/>
Barrientos García<br/>
21001538<br/>
Guatemala, 19 de septiembre de 2021<br/>
</p>

In [2]:
import numpy as np

In [3]:
def sigmoid(X):
  return 1/(1 + np.exp(-X))

def derivative_sigmoid(X):
  return sigmoid(X)*(1 - sigmoid(X))

![Artificial Neural Network](ann.png "Imagen 1 - Base para backpropagation")
<center>Imagen 1 - Red neuronal base para backpropagation</center>

In [71]:
# inputs = np.random.normal(0, 0.01, 3)
all_inputs = [np.array([0.0005353, 0.01432892, 0.00888838])]
# outputs = np.random.normal(0, 0.03, 2)
observations = np.array([0.00289363, 0.01488721])

layers = 2 + 1 # hidden + output
weights_layer = [
    [np.array([0.3, 0.46, 0.02]), 
     np.array([0.22, -0.7, 0.65]), 
     np.array([0.65, 0.9, 0.34])],
    [np.array([-0.3, 0.62, 0.45]), np.array([0.45, 0.57, 0.48]), np.array([0.65, 0.58, -0.45])],
    [np.array([-0.23, 0.22, 0.77]), np.array([0.9, 0.88, -0.4])]
]
weights_layer = [
    np.array([[0.3, 0.46, 0.02], 
     [0.22, -0.7, 0.65], 
     [0.65, 0.9, 0.34]]),
    np.array([[-0.3, 0.62, 0.45], [0.45, 0.57, 0.48], [0.65, 0.58, -0.45]]),
    np.array([[-0.23, 0.22, 0.77], [0.9, 0.88, -0.4]])
]

for i in range(layers):
    neurons = len(weights_layer[i])
    tmp_h = []
    pd = []
    der_weights_neuro = []
    for k in range(neurons):
        # generate every h/z by layer
        h = np.dot(all_inputs[i], weights_layer[i][k])
        z = sigmoid(h)
        tmp_h.append(z)
        # chain rule: z=sigma(h); Grad_z= dh/dw * d/sigma(h)
        tmp_partial_literal = []
        for t in range(len(all_inputs[i])):
            tmp_partial_literal.append(all_inputs[i][t])
        # Cuando se evalue backpropagation, se debe multiplicar por la derivada de la funcion de activacion evaluada para
        # los valores w1*x1 + ... + wn*xn.   derivative_sigmoid(h)
        der_weights_neuro.append(np.array(tmp_partial_literal))        
    all_inputs.append(np.array(tmp_h))

# last position predicted value is
predicted = all_inputs[-1]
predicted

array([0.61574177, 0.71000659])

In [72]:
squared_error = (observations - predicted)**2
total_error = (1/2)*np.sum(squared_error)
total_error

0.42938689905656025

In [68]:
print("all_inputs:")
all_inputs

all_inputs:


[array([0.0005353 , 0.01432892, 0.00888838]),
 array([0.50173241, 0.49896624, 0.50406642]),
 array([0.59523972, 0.6796453 , 0.59596889]),
 array([0.61574177, 0.71000659])]

In [81]:
print("weights_layer:")
weights_layer

weights_layer:


[array([[ 0.3 ,  0.46,  0.02],
        [ 0.22, -0.7 ,  0.65],
        [ 0.65,  0.9 ,  0.34]]),
 array([[-0.3 ,  0.62,  0.45],
        [ 0.45,  0.57,  0.48],
        [ 0.65,  0.58, -0.45]]),
 array([[-0.23,  0.22,  0.77],
        [ 0.9 ,  0.88, -0.4 ]])]

## Backpropagation

In [85]:
new_weights_layer = []
alpha = 0.005
lys = layers + 1 # +1 por el output
cum_error = []
for l in reversed(range(1, lys)):
    neurons = all_inputs[l]
    curr_error = []
    newweights = []
    print("-----------------------------------------------")
    for r in range(len(neurons)):
        if (l == layers):
            error_i = -(observations[r] - predicted[r])
            hr = np.dot(all_inputs[l-1], weights_layer[l-1][r])
            z = sigmoid(hr)
            der_af = z * (1 - z)      # activation function derivate
            df_dwi = all_inputs[l][r] # function's partial derivate: x1*w1 + ... + xn*wn
            gradient = error_i * der_af * df_dwi
#             print(">", gradient)
#             print(">>>", (weights_layer[l-1][r] - alpha*gradient))
            curr_error.append(error_i * der_af)
            newweights.append(weights_layer[l-1][r] - alpha*gradient)
        else:
            #1
            error_i = weights_layer[l][:,r] * cum_error[-1]
            #2
            hr = np.dot(all_inputs[l-1], weights_layer[l-1][r])
            z = sigmoid(hr)
            der_af = z * (1 - z)      # activation function derivate
            #3
            df_dwi = all_inputs[l][r] # function's partial derivate: x1*w1 + ... + xn*wn
            gradient = der_af * df_dwi
#             print(">", gradient)
#             print(">>>", (weights_layer[l-1][r] - alpha*gradient))
            curr_error.append(error_i * der_af)
            newweights.append(weights_layer[l-1][r] - alpha*gradient)
    cum_error.append(np.array(curr_error))
    new_weights_layer.append(np.array(newweights))


-----------------------------------------------
-----------------------------------------------
-----------------------------------------------


ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [87]:
print("weights_layer:")
weights_layer

weights_layer:


[array([[ 0.3 ,  0.46,  0.02],
        [ 0.22, -0.7 ,  0.65],
        [ 0.65,  0.9 ,  0.34]]),
 array([[-0.3 ,  0.62,  0.45],
        [ 0.45,  0.57,  0.48],
        [ 0.65,  0.58, -0.45]]),
 array([[-0.23,  0.22,  0.77],
        [ 0.9 ,  0.88, -0.4 ]])]

In [88]:
print("new_weights_layer:")
list(reversed(new_weights_layer))

new_weights_layer:


[array([[-0.30071705,  0.61928295,  0.44928295],
        [ 0.44926011,  0.56926011,  0.47926011],
        [ 0.64928248,  0.57928248, -0.45071752]]),
 array([[-0.23044642,  0.21955358,  0.76955358],
        [ 0.89949191,  0.87949191, -0.40050809]])]