Universidad Galileo  
Maestría en Data Science  
Statistical Learning II
Sección U  


   # **Practica 4: Backpropagation**


<p style="text-align: right;">
Henry Giovanni<br/>
Barrientos García<br/>
21001538<br/>
Guatemala, 19 de septiembre de 2021<br/>
</p>

In [9]:
import numpy as np

In [42]:
def sigmoid(X):
  return 1/(1 + np.exp(-X))

def derivative_sigmoid(X):
  return sigmoid(X)*(1 - sigmoid(X))

![Artificial Neural Network](ann.png "Imagen 1 - Base para backpropagation")
<center>Imagen 1 - Red neuronal base para backpropagation</center>

In [57]:
# inputs = np.random.normal(0, 0.01, 3)
all_inputs = [np.array([0.0005353, 0.01432892, 0.00888838])]
# outputs = np.random.normal(0, 0.03, 2)
observations = np.array([0.00289363, 0.01488721])

layers = 2 + 1 # hidden + output
weights_layer = [
    [np.array([0.3, 0.46, 0.02]), 
     np.array([0.22, -0.7, 0.65]), 
     np.array([0.65, 0.9, 0.34])],
    [np.array([-0.3, 0.62, 0.45]), np.array([0.45, 0.57, 0.48]), np.array([0.65, 0.58, -0.45])],
    [np.array([-0.23, 0.22, 0.77]), np.array([0.9, 0.88, -0.4])]
]

partial_derivatives_layer = []

for i in range(layers):
    neurons = len(weights_layer[i])
    tmp_h = []
    pd = []
    der_weights_neuro = []
    for k in range(neurons):
        # generate every h/z by layer
        h = np.dot(all_inputs[i], weights_layer[i][k])
        z = sigmoid(h)
        tmp_h.append(z)
        # chain rule: z=sigma(h); Grad_z= dh/dw * d/sigma(h)
        tmp_partial_literal = []
        for t in range(len(all_inputs[i])):
            tmp_partial_literal.append(all_inputs[i][t])
        # Cuando se evalue backpropagation, se debe multiplicar por la derivada de la funcion de activacion evaluada para
        # los valores w1*x1 + ... + wn*xn.   derivative_sigmoid(h)
        der_weights_neuro.append(np.array(tmp_partial_literal))
        
#         partial_derivatives.append(np.array([
#             all_inputs[i][0],
#             all_inputs[i][1],
#             all_inputs[i][2],
#         ]))
    partial_derivatives_layer.append(der_weights_neuro)
    all_inputs.append(np.array(tmp_h))

# last position predicted value is
predicted = all_inputs[-1]
predicted

array([0.61574177, 0.71000659])

In [58]:
squared_error = (observations - predicted)**2
total_error = (1/2)*np.sum(squared_error)
total_error

0.42938689905656025

In [59]:
print("Derivadas parciales en cada neurona:")
partial_derivatives_layer

Derivadas parciales en cada neurona:


[[array([0.0005353 , 0.01432892, 0.00888838]),
  array([0.0005353 , 0.01432892, 0.00888838]),
  array([0.0005353 , 0.01432892, 0.00888838])],
 [array([0.50173241, 0.49896624, 0.50406642]),
  array([0.50173241, 0.49896624, 0.50406642]),
  array([0.50173241, 0.49896624, 0.50406642])],
 [array([0.59523972, 0.6796453 , 0.59596889]),
  array([0.59523972, 0.6796453 , 0.59596889])]]

## Backpropagation

In [72]:
e0 = -(observations[0] - predicted[0])
e1 = -(observations[1] - predicted[1])

for l in reversed(range(layers+1)): # +1 por el output
    neurons = all_inputs[l]
    for r in range(len(neurons)):
        if (l == layers+1):
            hr = np.dot(all_inputs[l], weights_layer[l][r])
            z = sigmoid(hr)
            der_z = z(1-z) * all_inputs[l][]
    
    for r in range(len(neurons)):
        v = all_inputs[l][r]
        v = v*(1-v) #derivada de funcion de costo
        if (l == layers+1):
            h = np.dot(all_inputs[i], weights_layer[i][k])
            z = sigmoid(h)
        
            for k in range(len(partial_derivatives_layer[r])):
                s = partial_derivatives_layer[r][k]
                s = e0*v*s
                print("S:::", s)
                e0=1


S::: [7.76196911e-05 2.07772528e-03 1.28883488e-03]
S::: [0.00012665 0.00339028 0.00210302]
S::: [0.00012665 0.00339028 0.00210302]
S::: [0.10330531 0.10273577 0.10378588]
S::: [0.10330531 0.10273577 0.10378588]
S::: [0.10330531 0.10273577 0.10378588]
S::: [0.00012897 0.00345226 0.00214147]
S::: [0.00012897 0.00345226 0.00214147]
S::: [0.00012897 0.00345226 0.00214147]
S::: [0.10924098 0.10863871 0.10974915]
S::: [0.10924098 0.10863871 0.10974915]
S::: [0.10924098 0.10863871 0.10974915]
S::: [0.14332776 0.16365177 0.14350333]
S::: [0.14332776 0.16365177 0.14350333]
S::: [0.00013382 0.00358219 0.00222207]
S::: [0.00013382 0.00358219 0.00222207]
S::: [0.00013382 0.00358219 0.00222207]
S::: [0.12543257 0.12474103 0.12601607]
S::: [0.12543257 0.12474103 0.12601607]
S::: [0.12543257 0.12474103 0.12601607]
S::: [0.14880009 0.16990009 0.14898237]
S::: [0.14880009 0.16990009 0.14898237]
S::: [2.86392702e-07 7.66616498e-06 4.75540288e-06]
S::: [2.86392702e-07 7.66616498e-06 4.75540288e-06]
S:::

In [69]:
len(all_inputs[0])
all_inputs#[0][1]

[array([0.0005353 , 0.01432892, 0.00888838]),
 array([0.50173241, 0.49896624, 0.50406642]),
 array([0.59523972, 0.6796453 , 0.59596889]),
 array([0.61574177, 0.71000659])]